# Generated by Django 4.1.5 on 2023-02-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_studentmodel_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Bookmodels',
        ),
    ]
